VPTExtra/VPTExtra/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace VPTExtra.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

VPTExtra/VPTExtra/Pages/EventOverview.cshtml.cs
using Interfaces;
using Interfaces.Logic;
using Interfaces.DataAcces.API;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using Models;

namespace VPTExtra.Pages
{
    public class EventOverviewModel : PageModel
    {
        private readonly IEventService _eventService;
        private readonly IVisitorPlacementService _visitorPlacementService;
        private readonly IEventEditService _eventEditService;

        private readonly IEventApiService _apiService;

        public Event currentEvent { get; set; }
        private Event tempEvent { get; set; }
        [BindProperty]
        public int currentUserId {  get; set; }
        public string ErrorMessage {  get; set; }

        public EventOverviewModel(IEventService eventService, IVisitorPlacementService visitorPlacementService, IEventEditService eventEditService, IEventApiService apiService)
        {
            _eventService = eventService;
            _visitorPlacementService = visitorPlacementService;
            _eventEditService = eventEditService;
            _apiService = apiService;
        }
        public async Task<IActionResult> OnGet(int eventId)
        {
            currentUserId = (int)HttpContext.Session.GetInt32("uId");

            try
            {
                if (currentUserId != null)
                {
                    //tempEvent = _eventService.GetEventById(eventId);
                    tempEvent = await _apiService.GetEventById(eventId);

                    if (tempEvent != null)
                    {
                        currentEvent = tempEvent;
                        TempData["eventId"] = eventId;
                    }
                    else
                    {
                        return RedirectToPage("/Index");
                    }
                    return Page();
                }
                else
                {
                    return RedirectToPage("/Account/Login");
                }
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error retrieving event.";
                return Page();
            }
            
        }

        public IActionResult OnPostPlaceVisitor(int chairId)
        {
            int visitorId = (int)HttpContext.Session.GetInt32("uId");

            int eventId = Convert.ToInt32(TempData["eventId"]);

            try
            {
                _visitorPlacementService.PlaceVisitor(chairId, visitorId, eventId);

                return RedirectToPage(new { eventId = eventId });
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error placing visitor.";
                return Page();
            }
        }

        public IActionResult OnPostRevertPlacement(int chairId)
        {
            int visitorId = (int)HttpContext.Session.GetInt32("uId");

            int eventId = Convert.ToInt32(TempData["eventId"]);

            try
            {
                _visitorPlacementService.RevertVisitorPlacement(chairId, visitorId, eventId);

                return RedirectToPage(new { eventId = eventId });
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error undoing placement.";

                return Page();
            }
        }

        
        public IActionResult OnPostAddPart(int eventId)
        {
            _eventEditService.AddPart(eventId);

            return RedirectToPage(new { eventId = eventId });
        }
        public IActionResult OnPostAddRow(int partId)
        {
            int eventId = Convert.ToInt32(TempData["eventId"]);

            _eventEditService.AddRow(partId);

            return RedirectToPage(new { eventId = eventId });
        }
        public IActionResult OnPostAddChair(int rowId)
        {
            int eventId = Convert.ToInt32(TempData["eventId"]);

            _eventEditService.AddChair(rowId, eventId);

            return RedirectToPage(new { eventId = eventId });
        }
    }
}

VPTExtra/VPTExtra/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Logic.Services;
using Models;
using Interfaces;
using Interfaces.Logic;
using Interfaces.DataAcces.API;

namespace VPTExtra.Pages
{
    public class IndexModel : PageModel
    {
        private readonly IEventService _eventService;
        private readonly IEventApiService _apiService;
        //public List<Event> events { get; set; }
        public List<Event> events { get; set; }
        public string ErrorMessage { get; set; }
        public IndexModel(IEventService eventService, IEventApiService apiService)
        {
            _eventService = eventService;
            events = new List<Event>();
            _apiService = apiService;
        }
        public async Task<IActionResult> OnGet()
        {
            if (HttpContext.Session.GetInt32("uId") == null)
            {
                return RedirectToPage("/Account/Login");
            }

            try
            {
                events = await _apiService.GetEvents();

                //events = _eventService.GetAllEvents();
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error retrieving events.";
            }
            return Page();
        }
    }
}

VPTExtra/VPTExtra/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VPTExtra.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

VPTExtra/VPTExtra/Pages/EventOverview.cshtml
@page "/events/event/{eventId}"
@model VPTExtra.Pages.EventOverviewModel
@{
}
<link href="@Url.Content("~/css/event.css")" rel="stylesheet" type="text/css" />
<div class="scroll">
    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
    {
        <div class="alert alert-danger">
            @Model.ErrorMessage
        </div>
    }

    <article class="l-design-widht">
        <div class="card card--inverted">
            <h2>
                <svg class="icon" aria-hidden="true">
                    <use xlink:href="#icon-coffee" href="#icon-coffee" />
                </svg>Choose your seat
            </h2>
            <h4>Event: @Model.currentEvent.Location</h4>
            <h4>Start date: @Model.currentEvent.StartDate</h4>
            <h4>End date: @Model.currentEvent.EndDate</h4>
        </div>

        <div class="card card--inverted">
            <h2>Colors</h2>
            <button style="background-color: #d7d7d7;background-image: linear-gradient(147deg, #d7d7d7 0%, #353535 74%);height: 20px;">Your seats</button>
            <br />
            <button style="background: linear-gradient(109.6deg, rgb(36, 45, 57) 11.2%, rgb(16, 37, 60) 51.2%, rgb(0, 0, 0) 98.6%); height: 20px;">Taken</button>
            <br />
            <button style="background-color: #4d4855; background-image: linear-gradient(147deg, #4d4855 0%, #000000 74%); height: 20px;">Available</button>
        </div>
    </article>

    <br />

    <div class="outer-box-frame">
        <div class="theatre">

            @foreach (var sector in Model.currentEvent.Parts)
            {
                <h3 style="color:white;"></h3>

                <div class="cinema-seats left">
                    @foreach (var row in sector.Rows)
                    {
                        <div class="cinema-row row-1">
                            <p style="font-weight:bold; color:white;">Row @row.Name</p>
                            @foreach (var seat in row.Chairs)
                            {
                                @if (seat.Uid != 0)
                                {
                                    @if (seat.Uid == Model.currentUserId)
                                    {
                                        <form method="post">
                                            <button type="submit" id="userChosenChair" style="background-color: #d7d7d7;background-image: linear-gradient(147deg, #d7d7d7 0%, #353535 74%);" asp-page-handler="RevertPlacement"
                                                    asp-route-chairId="@seat.Id" class="seat">
                                            </button>
                                        </form>
                                    }
                                    else
                                    {
                                        <button type="submit" id="reservedChair" style="background: linear-gradient(109.6deg, rgb(36, 45, 57) 11.2%, rgb(16, 37, 60) 51.2%, rgb(0, 0, 0) 98.6%); color:white;"
                                                asp-route-chairId="@seat.Id" class="seat">
                                        </button>
                                    }
                                }
                                else
                                {
                                    <form method="post">
                                        <button type="submit" id="availableChair" style="background-color: #4d4855; background-image: linear-gradient(147deg, #4d4855 0%, #000000 74%);" asp-page-handler="PlaceVisitor"
                                                asp-route-chairId="@seat.Id" class="seat">
                                        </button>
                                    </form>
                                }

                            }
                            @if (HttpContext.Session.GetInt32("uRoleId") == 2)
                            {
                                <form method="post">
                                    <button type="submit" style="color:white;" asp-page-handler="AddChair"
                                            asp-route-rowId="@row.Id">
                                        C +
                                    </button>
                                </form>
                            }
                        </div>
                    }
                </div>
                @if (HttpContext.Session.GetInt32("uRoleId") == 2)
                {
                    <form method="post" style="margin-top: -50px;">
                        <button type="submit" style="color:white;" asp-page-handler="AddRow"
                                asp-route-partId="@sector.Id">
                            R +
                        </button>
                    </form>
                }
            }
            @if (HttpContext.Session.GetInt32("uRoleId") == 2)
            {
                <form method="post" style="margin-top: -50px;">
                    <button type="submit" style="color:white;" asp-page-handler="AddPart"
                            asp-route-eventId="@Model.currentEvent.Id">
                        P +
                    </button>
                </form>
            }
        </div>
    </div>
</div>
<script>
    $('.cinema-seats .seat').on('click', function () {
        $(this).toggleClass('active');
    });
</script> 

VPTExtra/VPTExtra/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}
<head>
    <link href="@Url.Content("~/css/EventsOverview.css")" rel="stylesheet" type="text/css" />
</head>
<div class="scroll">
    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
    {
        <div class="alert alert-danger">
            @Model.ErrorMessage
        </div>
    }
    <div class="outer-box-frame">

        @if (Model.events != null && Model.events.Any())
        {
            <div class="overview">
                @foreach (var item in Model.events)
                {
                    <article class="profile">
                        <h2 class="profile-username">@item.Location</h2>
                        <small class="profile-user-handle">@item.StartDate</small>
                        <small class="profile-user-handle">@Html.Raw(item.VisitorLimit - item.ChairsReserved) seat(s) left</small>
                        <div class="profile-actions">
                            <a class="btn btn--primary" asp-page="/EventOverview" asp-route-eventId="@item.Id">Enter</a>
                        </div>
                    </article>
                }
            </div>
        }
        else
        {
            <p>No events available.</p>
        }
    </div>
</div>