VPTExtra/VPTExtra/Pages/Manager/CreateEvent.cshtml.cs
using Interfaces.Logic;
using Interfaces.Repositories;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;

namespace VPTExtra.Pages.Manager
{
    public class CreateEventModel : PageModel
    {
        [BindProperty]
        public Event currentEvent {  get; set; }
        [BindProperty]
        public int AmountOfParts { get; set; }
        [BindProperty]
        public int AmountOfRows { get; set; }
        public string ErrorMessage { get; set; }
        private readonly IEventGenerationService _eventGenerationService;
        public CreateEventModel(IEventGenerationService eventGenerationService) 
        { 
            _eventGenerationService = eventGenerationService;
        }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("uRoleId") != 2)
            {
                return RedirectToPage("/Account/Login");
            }
            return null;
        }
        public IActionResult OnPostGenerateEvent() 
        {
            try
            {
                _eventGenerationService.GenerateEvent(currentEvent, AmountOfParts, AmountOfRows);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error creating event.";
                return Page();
            }

        }
    }
}

VPTExtra/VPTExtra/Pages/Manager/EventsOverview.cshtml.cs
using Interfaces;
using Interfaces.Logic;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;

namespace VPTExtra.Pages.Manager
{
    public class EventsOverviewModel : PageModel
    {
        private readonly IEventService _eventService;
        public List<Event> events { get; set; }
        public string ErrorMessage { get; set; }

        public EventsOverviewModel(IEventService eventService)
        {
            _eventService = eventService;
            events = new List<Event>();
        }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("uId") == null)
            {
                return RedirectToPage("/Account/Login");
            }
            else if (HttpContext.Session.GetInt32("uRoleId") != 2)
            {
                return RedirectToPage("/Index");
            }

            try
            {
                events = _eventService.GetAllEvents();
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error retrieving events.";
            }
            return Page();
        }

        public IActionResult OnPostDelete(int id)
        {
            try
            {
                _eventService.DeleteEvent(id);
                return RedirectToPage();
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error deleting event.";
                return Page();
            }
        }
    }
}

VPTExtra/VPTExtra/Pages/Manager/CreateEvent.cshtml
@page "/manager/events/create"
@model VPTExtra.Pages.Manager.CreateEventModel
@{
}
<head>
    <link href="@Url.Content("~/css/ManageEvents.css")" rel="stylesheet" type="text/css" />
</head>

<body>
    <div class="scroll">
        @if (!string.IsNullOrEmpty(Model.ErrorMessage))
        {
            <div class="alert alert-danger">
                @Model.ErrorMessage
            </div>
        }
        <div id="popup-container" style="display:none; text-align:center;" class="popup-container">
            <button style="width:20%; margin-left:15px;" class="btn btn--primary" onclick="closePopup()">Event created.</button>
        </div>
        <div class="outer-box-frame">
            <h5>
                <ins style="color: white;">
                    Only limit and dates are required, everything else is optional: if you only want to dictate how many visitors are allowed then the systems generates the
                    rest automatically based on that.
                </ins>
            </h5>
            <form method="post">
                <div class="form-group">
                    <label style="color: white;">Total amount of seats</label>
                    <input required type="number" id="VisitorLimit" name="currentEvent.VisitorLimit" asp-for="currentEvent.VisitorLimit" />
                    <small style="color: gray;" class="form-text text-muted">**</small>
                </div>
                <div class="form-group">
                    <label style="color: white;">Amount of parts (total)</label>
                    <input type="number" min="0" id="AmountOfParts" name="AmountOfParts" asp-for="AmountOfParts" />
                    <small style="color: gray;" class="form-text text-muted">Optional</small>
                </div>
                <div class="form-group">
                    <label style="color: white;">
                        Amount of rows (per part, if 0 it generates 6 per part)
                    </label>
                    <input type="number" max="15" min="0" id="AmountOfRows" name="AmountOfRows" asp-for="AmountOfRows" />
                    <small style="color: gray;" class="form-text text-muted">Optional (MAX: 15)</small>
                </div>
                <div class="form-group">
                    <label style="color: white;">Start date</label>
                    <input required type="date" id="StartDate" name="currentEvent.StartDate" asp-for="currentEvent.StartDate" />
                    <small style="color: gray;" class="form-text text-muted">Required</small>
                </div>
                <div class="form-group">
                    <label style="color: white;">End date</label>
                    <input required type="date" id="EndDate" name="currentEvent.EndDate" asp-for="currentEvent.EndDate" />
                    <small style="color: gray;" class="form-text text-muted">Required</small>
                </div>
                <button type="submit" asp-page-handler="GenerateEvent" onclick="confirmDeletion()" class="btn btn-primary">Create event</button>
            </form>
        </div>
    </div>
</body>
<script>
    document.addEventListener('DOMContentLoaded', function () {
        const popupDisplayed = sessionStorage.getItem('popupCreateEventDisplayed');
        if (popupDisplayed === 'true') {
            showPopup();
        }
    });

    function confirmDeletion() {
        let text;
        if (confirm("Delete event?") == true) {
            showPopup();
        }
    }

    function showPopup() {
        document.getElementById('popup-container').style.display = 'flex';
        // Store popup state in sessionStorage
        sessionStorage.setItem('popupCreateEventDisplayed', 'true');
    }

    function closePopup() {
        document.getElementById('popup-container').style.display = 'none';
        // Remove popup state from sessionStorage
        sessionStorage.removeItem('popupCreateEventDisplayed');
    }

</script>

VPTExtra/VPTExtra/Pages/Manager/EventsOverview.cshtml
@page "/manager/events/overview"
@model VPTExtra.Pages.Manager.EventsOverviewModel
@{
}
<head>
    <link href="@Url.Content("~/css/ManageEvents.css")" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="scroll">

    @if (!string.IsNullOrEmpty(Model.ErrorMessage))
    {
        <div class="alert alert-danger">
            @Model.ErrorMessage
        </div>
    }
    <div class="outer-box-frame">

        <div class="container">
            <ul class="responsive-table">
                <li class="table-header">
                    <div class="col col-1">Id</div>
                    <div class="col col-2">Name</div>
                    <div class="col col-3">Start Date</div>
                    <div class="col col-4">End Date</div>
                    <div class="col col-5">Visitor Limit</div>
                    <div class="col col-6">Chairs reserved</div>
                    <div class="col col-7"></div>
                </li>
                @foreach (var item in Model.events)
                {
                    <li class="table-row">
                        <div class="col col-1"><a class="btn btn-primary" style="background:blue; width: 60px;" asp-page="../EventOverview" asp-route-eventId="@item.Id">View</a></div>
                        <div class="col col-2">@item.Location</div>
                        <div class="col col-3">@item.StartDate</div>
                        <div class="col col-4">@item.EndDate</div>
                        <div class="col col-5">@item.VisitorLimit</div>
                        <div class="col col-6">@item.ChairsReserved</div>
                        <div class="col col-7">
                            <form method="post">
                                <div class="profile-actions">
                                    <button type="submit" class="btn btn--primary" asp-page-handler="delete" onclick="return confirm('Are you sure?')"
                                            asp-route-id="@item.Id">
                                        delete
                                    </button>
                                </div>

                            </form>
                        </div>
                    </li>
                }
            </ul>
        </div>
    </div>
    </div>
</body>