VPTExtra/VPTExtra/Pages/Account/Login.cshtml.cs
using Interfaces;
using Interfaces.Logic;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;

namespace VPTExtra.Pages.Account
{
    public class LoginModel : PageModel
    {
        private readonly IUserService _userService;
        [BindProperty]
        public User userToLogin { get; set; }
        public string ErrorMessage { get; set; }

        public LoginModel(IUserService userService)
        {
            _userService = userService;
        }
        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("uId") != null)
            {
                return RedirectToPage("/Index");
            }
            return Page();
        }
        public IActionResult OnPostLogin()
        {
            try
            {
                User userToBeLogged = _userService.LoginUser(userToLogin);
                if (userToBeLogged != null)
                {
                    HttpContext.Session.SetInt32("uId", userToBeLogged.Id);
                    HttpContext.Session.SetString("uName", userToBeLogged.Name);
                    HttpContext.Session.SetInt32("uRoleId", userToBeLogged.RoleId);

                    return RedirectToPage("/Index");
                }
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                Page();
            }
            
            return null;
        }
    }
}

VPTExtra/VPTExtra/Pages/Account/Logout.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace VPTExtra.Pages.Account
{
    public class LogoutModel : PageModel
    {
        public IActionResult OnGet()
        {
            HttpContext.Session.Clear();
            return RedirectToPage("Login");
        }
    }
}

VPTExtra/VPTExtra/Pages/Account/Profile.cshtml.cs
using Interfaces.Logic;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;
using QRCoder;
using System.Drawing.Imaging;
using System.Drawing;
using Microsoft.Extensions.Logging;
using PdfSharp.Drawing;
using PdfSharp.Pdf;
using PdfSharp.UniversalAccessibility.Drawing;
using System;
using System.Collections.Generic;
using System.IO;
using Logic.QRRelated;
using Newtonsoft.Json.Serialization;

namespace VPTExtra.Pages.Account
{
    public class ProfileModel : PageModel
    {
        public List<Event> visitorEvents { get; set; }
        public User user { get; set; }
        public string ErrorMessage { get; set; }
        public string QrCodeImageBase64 { get; set; }

        private readonly IUserProfileService _userProfileDataService;
        private readonly IUserService _userService;
        public ProfileModel(IUserProfileService userProfileDataService, IUserService userService)
        {
            _userProfileDataService = userProfileDataService;
            _userService = userService;
            user = new User();
            visitorEvents = new List<Event>();
        }

        public IActionResult OnGet()
        {
            if (HttpContext.Session.GetInt32("uId") == null)
            {
                return RedirectToPage("/Account/Login");
            }

            int userId = (int)HttpContext.Session.GetInt32("uId");

            try
            {
                user = _userService.GetVisitorById(userId);

                visitorEvents = _userProfileDataService.RetrieveUserEvents(userId);

                foreach (var item in visitorEvents)
                {
                    int eventId = item.Id;
                    string url = Url.Page("/QRCode/TicketDownloadPage", "Scan", new { userId = userId, eventId = eventId }, Request.Scheme);

                    item.EventQr = GenerateQRCode(url);
                }
            }
            catch (Exception ex)
            {
                ErrorMessage = "Error retrieving profile data.";
            }
            return Page();
        }

        private string GenerateQRCode(string url)
        {
            using (QRCodeGenerator qrGenerator = new QRCodeGenerator())
            {
                QRCodeData qrCodeData = qrGenerator.CreateQrCode(url, QRCodeGenerator.ECCLevel.Q);
                using (QRCoder.QRCode qrCode = new QRCoder.QRCode(qrCodeData))
                using (Bitmap qrCodeImage = qrCode.GetGraphic(20))
                {
                    using (MemoryStream ms = new MemoryStream())
                    {
                        qrCodeImage.Save(ms, ImageFormat.Png);
                        byte[] byteImage = ms.ToArray();
                        return Convert.ToBase64String(byteImage);
                    }
                }
            }
        }
    }
}

VPTExtra/VPTExtra/Pages/Account/Registration.cshtml.cs
using Interfaces.Logic;
using Logic.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Models;

namespace VPTExtra.Pages.Account
{
    public class RegistrationModel : PageModel
    {
        private readonly IUserService _userService;
        [BindProperty]       
        public User userToRegister { get; set; }
        public string ErrorMessage { get; set; }
        public RegistrationModel(IUserService userService)
        {
            _userService = userService;
        }
        public void OnGet()
        {

        }
        public IActionResult OnPostRegister() 
        {
            try
            {
                if (_userService.RegisterUser(userToRegister) != null)
                {
                    return RedirectToPage("/Account/Login");
                }
            }
            catch (Exception ex)
            {
                ErrorMessage = ex.Message;
                return Page();
            }
            return null;
        }
    }
}

VPTExtra/VPTExtra/Pages/Account/Login.cshtml
@page "/login"
@model VPTExtra.Pages.Account.LoginModel
@{
}
<br />
<br />
<br />
@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}
<form method="post" asp-page-handler="Login">
    <div class="form-outline mb-4">
        <input class="form-control" required asp-for="@Model.userToLogin.Name">
        <label class="form-label" style="color:white;" for="form2Example1">User name</label>
    </div>

    <div class="form-outline mb-4">
        <input class="form-control" required type="email" asp-for="@Model.userToLogin.Email">
        <label class="form-label" style="color:white;" for="form2Example1">Email address</label>
    </div>

    <div class="form-outline mb-4">
        <input class="form-control" required type="password" asp-for="@Model.userToLogin.Password">
        <label class="form-label" style="color:white;" for="form2Example2">Password</label>
    </div>


    <button type="submit" class="btn btn-primary btn-block mb-4">Sign in</button>

    <div class="text-center">
        <p style="color:white;">Not a member? <a asp-page="Registration" style="color:lightblue;">Register</a></p>     
    </div>
</form>

VPTExtra/VPTExtra/Pages/Account/Logout.cshtml
@page
@model VPTExtra.Pages.Account.LogoutModel
@{
}

VPTExtra/VPTExtra/Pages/Account/Profile.cshtml
@page "/profile"
@model VPTExtra.Pages.Account.ProfileModel
@{
}
@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}
<section style="background-color: #eee;">
    <div class="row">
        <div class="col-lg-4">
            <div class="card mb-4">
                <div class="card-body text-center">
                    <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava3.webp" alt="avatar"
                         class="rounded-circle img-fluid" style="width: 150px;">
                    <h5 class="my-3">@Model.user.Name</h5>
                    <p class="text-muted mb-1">@Model.user.Email</p>
                    @* <p class="text-muted mb-4">Role: @Model.user</p> *@
                    <div class="d-flex justify-content-center mb-2">
                        
                    </div>
                </div>
            </div>
            <div class="card mb-4 mb-lg-0">
                <div class="card-body p-0">
                    <ul class="list-group list-group-flush rounded-3">
                        @foreach (var item in Model.visitorEvents)
                        {
                            <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                <i class="fab fa-facebook-f fa-lg" style="color: #3b5998;">Events joined: </i>
                                <p style="font-weight:bold;" class="mb-0">@item.Location </p>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-lg-8">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-3">                           
                            <p class="mb-0">Full Name</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.user.Name</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <p class="mb-0">Email</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">@Model.user.Email</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <p class="mb-0">Phone</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">(097) 234-5678</p>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-sm-3">
                            <p class="mb-0">Mobile</p>
                        </div>
                        <div class="col-sm-9">
                            <p class="text-muted mb-0">(098) 765-4321</p>
                        </div>
                    </div>
                    <hr>
                    @*  <div class="row">
                    <div class="col-sm-3">
                    <p class="mb-0">Role</p>
                    </div>
                    <div class="col-sm-9">
                    <p class="text-muted mb-0">@Model.user.Role.RoleName</p>
                    </div>
                    </div> *@
                </div>
            </div>
            <div class="row">
                <p class="mb-0">Your events:</p>
                @foreach (var item in Model.visitorEvents)
                {
                    <div class="col-md-6">
                        <div class="card mb-4 mb-md-0">
                            <div class="card-body">
                                <p class="mb-4">
                                    <span class="text-primary font-italic me-1">
                                        <a asp-page="/EventOverview" asp-route-eventId="@item.Id">@item.Location</a>
                                    </span>
                                </p>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">Your seats: @item.ChairsReserved
                                    @if (!string.IsNullOrEmpty(item.EventQr))
                                    {
                                        <img src="data:image/png;base64,@item.EventQr" style="height: 70px; width: 70px;" alt="QR Code" />
                                    }
                                </p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 72%" aria-valuenow="72"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
   @*                              <p class="mt-4 mb-1" style="font-size: .77rem;">@item.Movie.MovieDirector</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 89%" aria-valuenow="89"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">@item.Movie.MovieLanguage</p>
                                <div class="progress rounded" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 55%" aria-valuenow="55"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">@item.Movie.MovieReleaseDate</p>
                                <div class="progress rounded mb-2" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">@Model.movieService.TryGetAverageRating(item.Movie.MovieId)</p>
                                <div class="progress rounded mb-2" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                                <p class="mt-4 mb-1" style="font-size: .77rem;">@Model.movieService.TryGetCategories(item.Movie.MovieId)</p>
                                <div class="progress rounded mb-2" style="height: 5px;">
                                    <div class="progress-bar" role="progressbar" style="width: 66%" aria-valuenow="66"
                                         aria-valuemin="0" aria-valuemax="100"></div>
                                </div> *@
                            </div>
                        </div>
                        <br />
                    </div>
                }

            </div>
        </div>
    </div>
    </div>
</section>

VPTExtra/VPTExtra/Pages/Account/Registration.cshtml
@page "/register"
@model VPTExtra.Pages.Account.RegistrationModel
@{
}
<br />
<br />
<br />
@if (!string.IsNullOrEmpty(Model.ErrorMessage))
{
    <div class="alert alert-danger">
        @Model.ErrorMessage
    </div>
}
<form method="post" asp-page-handler="Register">
    <div class="form-outline mb-4">
        <input class="form-control" required asp-for="@Model.userToRegister.Name">
        <label class="form-label" style="color:white;" for="form3Example1cg">Your Name</label>
    </div>

    <div class="form-outline mb-4">
        <input class="form-control" required type="email" asp-for="@Model.userToRegister.Email">
        <label class="form-label" style="color:white;" for="form3Example3cg">Your Email</label>
    </div>

    <div class="form-outline mb-4">
        <input class="form-control" required type="password" asp-for="@Model.userToRegister.Password">
        <label class="form-label" style="color:white;">Password</label>
    </div>

    <div class="d-flex justify-content-center">
        <button type="submit" 
                class="btn btn-primary btn-block mb-4">
            Register
        </button>
    </div>

    <p style="color:white;" class="text-center mt-5 mb-0">
        Have already an account? <a asp-page="Login"
                                     style="color:lightblue;"><u>Login here</u></a>
    </p>
</form>